#!/usr/bin/env python3
"""
Project A V2 UART upgrader.

This client sends a packaged firmware image (generated by tools/pack_fw.py)
through the text command channel:
  UPG_BEGIN / UPG_DATA / UPG_END / UPG_STATUS / UPG_ACTIVATE / UPG_CONFIRM
"""

from __future__ import annotations

import argparse
import re
import struct
import time
import zlib
from pathlib import Path

import serial
import serial.tools.list_ports


MAGIC = b"PAFW"
HEADER_FMT = "<4sHHIIHHHI16s12s10s"
HEADER_SIZE = struct.calcsize(HEADER_FMT)
NACK_RE = re.compile(r"^UPG_NACK\s+(\w+)\s+(\S+)")
ACK_DATA_RE = re.compile(r"^UPG_ACK DATA off=(\d+)$")
CAP_RE = re.compile(r"^CAP:upgrade_uart=(\d+),max_chunk=(\d+),dual_slot=(\d+)$")
STATUS_RE = re.compile(r"^UPG_STATUS:([^,]+),off=(\d+),err=(.+)$")
BOOT_RE = re.compile(r"^BOOT:active=.*$")


def list_candidate_ports(preferred: str) -> list[str]:
    if preferred.lower() != "auto":
        return [preferred]
    ports = list(serial.tools.list_ports.comports())
    ch340 = sorted([p.device for p in ports if "CH340" in (p.description or "").upper()])
    others = sorted(
        [p.device for p in ports if p.device not in ch340 and p.device.upper().startswith("COM")]
    )
    return ch340 + others


def open_serial(preferred: str, baud: int, timeout: float) -> tuple[serial.Serial, str]:
    for port in list_candidate_ports(preferred):
        try:
            ser = serial.Serial(port, baudrate=baud, timeout=timeout)
            return ser, port
        except serial.SerialException:
            continue
    raise RuntimeError(f"No usable serial port for --port {preferred}")


def send_cmd(
    ser: serial.Serial,
    cmd: str,
    *,
    char_delay_ms: int = 0,
    preflush_newlines: int = 0,
) -> None:
    payload = (cmd + "\n").encode("ascii")

    # Optional parser flush for noisy links: push a few newlines so stale
    # partial commands are terminated before sending the next command.
    if preflush_newlines > 0:
        ser.write(b"\n" * preflush_newlines)
        ser.flush()
        time.sleep(0.02)

    if char_delay_ms <= 0:
        ser.write(payload)
        ser.flush()
    else:
        delay_s = char_delay_ms / 1000.0
        for b in payload:
            ser.write(bytes([b]))
            ser.flush()
            time.sleep(delay_s)

    print(f"[TX] {cmd}")


def read_package(pkg_path: Path) -> dict:
    blob = pkg_path.read_bytes()
    if len(blob) < HEADER_SIZE:
        raise ValueError(f"Package too small: {len(blob)} bytes")

    (
        magic,
        header_size,
        header_ver,
        image_size,
        image_crc,
        vmaj,
        vmin,
        vpat,
        build_unix,
        board_raw,
        sha_raw,
        _reserved,
    ) = struct.unpack(HEADER_FMT, blob[:HEADER_SIZE])

    if magic != MAGIC:
        raise ValueError(f"Bad magic: {magic!r}")
    if header_size != HEADER_SIZE:
        raise ValueError(f"Bad header size: {header_size}, expected {HEADER_SIZE}")

    payload = blob[HEADER_SIZE : HEADER_SIZE + image_size]
    if len(payload) != image_size:
        raise ValueError(f"Payload truncated: expected {image_size}, got {len(payload)}")

    calc_crc = zlib.crc32(payload) & 0xFFFFFFFF
    if calc_crc != image_crc:
        raise ValueError(f"Payload CRC mismatch: header=0x{image_crc:08X} calc=0x{calc_crc:08X}")

    return {
        "version": f"{vmaj}.{vmin}.{vpat}",
        "build_unix": build_unix,
        "board": board_raw.rstrip(b"\x00").decode("ascii", errors="ignore"),
        "git_sha": sha_raw.rstrip(b"\x00").decode("ascii", errors="ignore"),
        "image_size": image_size,
        "image_crc32": image_crc,
        "payload": payload,
        "header_version": header_ver,
        "pkg_path": str(pkg_path),
    }


def wait_for_match(
    ser: serial.Serial,
    timeout_s: float,
    patterns: list[tuple[str, re.Pattern[str]]],
) -> tuple[str | None, re.Match[str] | None, str | None]:
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        line = ser.readline().decode("utf-8", errors="replace").strip()
        if not line:
            continue
        print(f"[RX] {line}")
        for name, pat in patterns:
            m = pat.match(line)
            if m:
                return name, m, line
    return None, None, None


def query_optional(
    ser: serial.Serial,
    cmd: str,
    pat: re.Pattern[str],
    timeout_s: float,
    retries: int,
    char_delay_ms: int,
    preflush_newlines: int,
) -> str | None:
    attempts = max(1, retries)
    for idx in range(1, attempts + 1):
        send_cmd(
            ser,
            cmd,
            char_delay_ms=char_delay_ms,
            preflush_newlines=preflush_newlines,
        )
        name, _m, line = wait_for_match(ser, timeout_s, [("ok", pat)])
        if name == "ok":
            return line
        print(f"[WARN] {cmd} response timeout (try {idx}/{attempts})")
    return None


def expect_ack(
    ser: serial.Serial,
    ack_pattern: re.Pattern[str],
    timeout_s: float,
    phase: str,
) -> re.Match[str]:
    name, match, line = wait_for_match(
        ser,
        timeout_s,
        [("ack", ack_pattern), ("nack", NACK_RE)],
    )
    if name == "ack" and match is not None:
        return match
    if name == "nack" and match is not None:
        cmd = match.group(1)
        err = match.group(2)
        raise RuntimeError(f"{phase} failed: {cmd} {err}")
    raise TimeoutError(f"{phase} timeout (no ACK/NACK)")


def do_upgrade(args: argparse.Namespace) -> int:
    pkg = read_package(Path(args.pkg).resolve())
    print(
        "[INFO] Package:",
        f"ver={pkg['version']}",
        f"size={pkg['image_size']}",
        f"crc=0x{pkg['image_crc32']:08X}",
        f"board={pkg['board']}",
        f"git={pkg['git_sha']}",
    )

    if args.dry_run:
        print("[INFO] Dry-run enabled, stop after package check.")
        return 0

    ser, port = open_serial(args.port, args.baud, args.read_timeout)
    print(f"[INFO] Serial opened: {port} @ {args.baud}")
    try:
        ctrl_delay_ms = (
            args.ctrl_char_delay_ms
            if args.ctrl_char_delay_ms >= 0
            else args.char_delay_ms
        )
        data_delay_ms = (
            args.data_char_delay_ms
            if args.data_char_delay_ms >= 0
            else args.char_delay_ms
        )

        if args.set_period_ms is not None:
            send_cmd(
                ser,
                f"SET_PERIOD {args.set_period_ms}",
                char_delay_ms=ctrl_delay_ms,
                preflush_newlines=args.preflush_newlines,
            )
            # Best effort: do not fail hard if this optional prep step times out.
            query_optional(
                ser,
                "GET_PERIOD",
                re.compile(r"^PERIOD:\d+$"),
                args.ack_timeout,
                retries=args.query_retries,
                char_delay_ms=ctrl_delay_ms,
                preflush_newlines=args.preflush_newlines,
            )

        # Optional info probes
        query_optional(
            ser,
            "GET_VER",
            re.compile(r"^VER:app=.*"),
            args.ack_timeout,
            retries=args.query_retries,
            char_delay_ms=ctrl_delay_ms,
            preflush_newlines=args.preflush_newlines,
        )
        cap_line = query_optional(
            ser,
            "GET_CAP",
            CAP_RE,
            args.ack_timeout,
            retries=args.query_retries,
            char_delay_ms=ctrl_delay_ms,
            preflush_newlines=args.preflush_newlines,
        )
        query_optional(
            ser,
            "GET_BOOTSTATE",
            BOOT_RE,
            args.ack_timeout,
            retries=args.query_retries,
            char_delay_ms=ctrl_delay_ms,
            preflush_newlines=args.preflush_newlines,
        )
        query_optional(
            ser,
            "UPG_STATUS",
            STATUS_RE,
            args.ack_timeout,
            retries=args.query_retries,
            char_delay_ms=ctrl_delay_ms,
            preflush_newlines=args.preflush_newlines,
        )

        chunk_size = args.chunk
        if cap_line:
            m = CAP_RE.match(cap_line)
            if m:
                cap_chunk = int(m.group(2))
                chunk_size = min(chunk_size, cap_chunk)
        chunk_size = max(1, min(chunk_size, 128))
        print(f"[INFO] Transfer chunk size: {chunk_size} bytes")

        send_cmd(
            ser,
            f"UPG_BEGIN {pkg['version']} {pkg['image_size']} 0x{pkg['image_crc32']:08X}",
            char_delay_ms=ctrl_delay_ms,
            preflush_newlines=args.preflush_newlines,
        )
        expect_ack(ser, re.compile(r"^UPG_ACK BEGIN off=0$"), args.ack_timeout, "UPG_BEGIN")

        payload: bytes = pkg["payload"]
        total = len(payload)
        offset = 0
        last_print = time.time()
        while offset < total:
            chunk = payload[offset : offset + chunk_size]
            chunk_crc = zlib.crc32(chunk) & 0xFFFFFFFF
            send_cmd(
                ser,
                f"UPG_DATA {offset} {chunk.hex().upper()} 0x{chunk_crc:08X}",
                char_delay_ms=data_delay_ms,
                preflush_newlines=args.preflush_newlines,
            )
            m = expect_ack(ser, ACK_DATA_RE, args.ack_timeout, f"UPG_DATA@{offset}")
            next_off = int(m.group(1))
            expected_off = offset + len(chunk)
            if next_off != expected_off:
                raise RuntimeError(
                    f"Offset mismatch: ack={next_off} expected={expected_off}"
                )
            offset = next_off
            if args.chunk_delay_ms > 0:
                time.sleep(args.chunk_delay_ms / 1000.0)
            now = time.time()
            if now - last_print > 0.2 or offset == total:
                pct = (offset * 100.0) / total
                print(f"[INFO] Progress: {offset}/{total} ({pct:.1f}%)")
                last_print = now

        send_cmd(
            ser,
            "UPG_END",
            char_delay_ms=ctrl_delay_ms,
            preflush_newlines=args.preflush_newlines,
        )
        expect_ack(ser, re.compile(r"^UPG_ACK END$"), args.ack_timeout, "UPG_END")

        if args.activate:
            send_cmd(
                ser,
                "UPG_ACTIVATE",
                char_delay_ms=ctrl_delay_ms,
                preflush_newlines=args.preflush_newlines,
            )
            expect_ack(
                ser,
                re.compile(r"^UPG_ACK ACTIVATE$"),
                args.ack_timeout,
                "UPG_ACTIVATE",
            )
            query_optional(
                ser,
                "GET_BOOTSTATE",
                BOOT_RE,
                args.ack_timeout,
                retries=args.query_retries,
                char_delay_ms=ctrl_delay_ms,
                preflush_newlines=args.preflush_newlines,
            )

        if args.confirm:
            send_cmd(
                ser,
                "UPG_CONFIRM",
                char_delay_ms=ctrl_delay_ms,
                preflush_newlines=args.preflush_newlines,
            )
            expect_ack(
                ser,
                re.compile(r"^UPG_ACK CONFIRM$"),
                args.ack_timeout,
                "UPG_CONFIRM",
            )
            query_optional(
                ser,
                "GET_BOOTSTATE",
                BOOT_RE,
                args.ack_timeout,
                retries=args.query_retries,
                char_delay_ms=ctrl_delay_ms,
                preflush_newlines=args.preflush_newlines,
            )

        query_optional(
            ser,
            "UPG_STATUS",
            STATUS_RE,
            args.ack_timeout,
            retries=args.query_retries,
            char_delay_ms=ctrl_delay_ms,
            preflush_newlines=args.preflush_newlines,
        )
        print("[OK] UART upgrade flow completed.")
        return 0
    except Exception as exc:
        print(f"[ERR] {exc}")
        if args.abort_on_fail:
            try:
                send_cmd(
                    ser,
                    "UPG_ABORT",
                    char_delay_ms=ctrl_delay_ms,
                    preflush_newlines=args.preflush_newlines,
                )
                expect_ack(
                    ser,
                    re.compile(r"^UPG_ACK ABORT$"),
                    args.ack_timeout,
                    "UPG_ABORT",
                )
            except Exception as abort_exc:
                print(f"[WARN] UPG_ABORT failed: {abort_exc}")
        return 2
    finally:
        ser.close()
        print("[INFO] Serial closed.")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Project A V2 UART upgrader")
    p.add_argument("--pkg", required=True, help="path to upgrade_package.bin")
    p.add_argument("--port", default="auto", help="COM port or auto")
    p.add_argument("--baud", type=int, default=115200, help="baud rate")
    p.add_argument("--chunk", type=int, default=128, help="chunk bytes (1~128)")
    p.add_argument("--read-timeout", type=float, default=0.2, help="serial read timeout seconds")
    p.add_argument("--ack-timeout", type=float, default=2.0, help="ACK wait timeout seconds")
    p.add_argument("--chunk-delay-ms", type=int, default=0, help="inter-chunk delay in ms")
    p.add_argument(
        "--query-retries",
        type=int,
        default=3,
        help="retry times for optional query commands (GET_*/UPG_STATUS)",
    )
    p.add_argument(
        "--set-period-ms",
        type=int,
        default=None,
        help="optional SET_PERIOD value before upgrade (e.g. 5000)",
    )
    p.add_argument(
        "--char-delay-ms",
        type=int,
        default=0,
        help="send each command byte with delay to improve reliability on noisy links",
    )
    p.add_argument(
        "--ctrl-char-delay-ms",
        type=int,
        default=-1,
        help="override control-command byte delay (ms), -1 means use --char-delay-ms",
    )
    p.add_argument(
        "--data-char-delay-ms",
        type=int,
        default=-1,
        help="override UPG_DATA byte delay (ms), -1 means use --char-delay-ms",
    )
    p.add_argument(
        "--preflush-newlines",
        type=int,
        default=0,
        help="prepend N newlines before each command to clear stale parser state",
    )
    p.add_argument("--activate", action="store_true", help="send UPG_ACTIVATE after UPG_END")
    p.add_argument("--confirm", action="store_true", help="send UPG_CONFIRM after activate")
    p.add_argument("--abort-on-fail", action="store_true", help="send UPG_ABORT when transfer fails")
    p.add_argument("--dry-run", action="store_true", help="verify package only, no serial transfer")
    return p


def main() -> int:
    args = build_parser().parse_args()
    if args.chunk < 1 or args.chunk > 128:
        raise SystemExit("--chunk must be in range 1~128")
    if args.confirm and not args.activate:
        raise SystemExit("--confirm requires --activate")
    return do_upgrade(args)


if __name__ == "__main__":
    raise SystemExit(main())
