#!/usr/bin/env python3
"""
Project A V2 boot policy simulator.

Run rollback decision flow locally using boot_state.bin generated by
boot_state_tool.py. This lets us validate policy behavior before external
flash arrives.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from boot_state_tool import (
    BootState,
    RESULT_ROLLBACK,
    SLOT_NONE,
    load_state,
    save_state,
    state_to_json,
)


def decide(state: BootState, max_attempts: int) -> str:
    if state.pending_slot == SLOT_NONE:
        return "boot_active"
    if max_attempts <= 0:
        return "stay_loader"
    if state.boot_attempts >= max_attempts:
        return "boot_active_rollback"
    return "boot_pending"


def step_once(state: BootState, max_attempts: int) -> str:
    action = decide(state, max_attempts)
    if action == "boot_pending":
        state.boot_attempts = min(255, state.boot_attempts + 1)
        state.seq += 1
        return "trial_pending_increment"
    if action == "boot_active_rollback":
        state.pending_slot = SLOT_NONE
        state.boot_attempts = 0
        state.last_result = RESULT_ROLLBACK
        state.seq += 1
        return "rollback_to_active"
    return action


def cmd_decide(args: argparse.Namespace) -> int:
    state = load_state(Path(args.input).resolve())
    out = state_to_json(state, {"decision": decide(state, args.max_attempts)})
    print(json.dumps(out, indent=2))
    return 0


def cmd_step(args: argparse.Namespace) -> int:
    src = Path(args.input).resolve()
    state = load_state(src)
    action = step_once(state, args.max_attempts)
    dst = Path(args.out).resolve() if args.out else src
    save_state(dst, state)
    out = state_to_json(state, {"action": action, "path": str(dst)})
    print(json.dumps(out, indent=2))
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Project A boot policy simulator")
    sub = p.add_subparsers(dest="cmd", required=True)

    p_decide = sub.add_parser("decide", help="print current boot decision")
    p_decide.add_argument("--input", required=True, help="path to boot_state.bin")
    p_decide.add_argument("--max-attempts", type=int, default=3)
    p_decide.set_defaults(func=cmd_decide)

    p_step = sub.add_parser("step", help="simulate one reboot decision step")
    p_step.add_argument("--input", required=True, help="path to boot_state.bin")
    p_step.add_argument("--max-attempts", type=int, default=3)
    p_step.add_argument("--out", help="optional output file path")
    p_step.set_defaults(func=cmd_step)

    return p


def main() -> int:
    args = build_parser().parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())

